// Generated by scripts/generate-demo-registry.ts — do not edit.
import type { ComponentType } from "react";

/** Demo name (relative to demos/, without extension) -> lazy module import. */
export const demoImports: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
  "button/default": () => import("@/demos/button/default"),
};
