"use client";

import {
  createContext,
  type ReactElement,
  use,
  useCallback,
  useId,
  useMemo,
  useState,
} from "react";
import type {
  CartesianGridProps,
  LegendPayload,
  LegendProps,
  TooltipProps,
  XAxisProps as XAxisPrimitiveProps,
  YAxisProps as YAxisPrimitiveProps,
} from "recharts";
import {
  CartesianGrid as CartesianGridPrimitive,
  Legend as LegendPrimitive,
  ResponsiveContainer,
  Tooltip as TooltipPrimitive,
  XAxis as XAxisPrimitive,
  YAxis as YAxisPrimitive,
} from "recharts";
import type { ContentType as LegendContentType } from "recharts/types/component/DefaultLegendContent";
import type {
  NameType,
  Props as TooltipContentProps,
  ValueType,
} from "recharts/types/component/DefaultTooltipContent";
import type { ContentType as TooltipContentType } from "recharts/types/component/Tooltip";

import { useIsMobile } from "../hooks/use-mobile";
import { cn } from "../utils/index";

// #region Types ------------------------------------------------------------

/**
 * Stacking behaviour shared by the cartesian chart wrappers.
 *
 * - `default` — each series drawn independently.
 * - `stacked` — series share a `stackId` and pile on top of each other.
 * - `percent` — stacked and normalised to 100% (recharts `stackOffset="expand"`).
 */
type ChartType = "default" | "stacked" | "percent";

/**
 * Orientation of a cartesian/radial chart.
 *
 * - `horizontal` — categories on the X-axis (the common case).
 * - `vertical` — categories on the Y-axis.
 * - `radial` — used by {@link PieChart}-style radial charts.
 */
type ChartLayout = "horizontal" | "vertical" | "radial";

/** Recharts axis tick interval strategy. */
type IntervalType = "preserveStartEnd" | "equidistantPreserveStart";

/** A loosely-typed chart data row. */
type ChartDatum = Record<string, unknown>;

/**
 * Per-series configuration consumed by every chart in the design system.
 *
 * Each key is a data series identifier mapping to a display label, an
 * optional icon component, and a color source. Colors may be one of the
 * built-in {@link CHART_COLORS} keys (e.g. `"chart-1"`), any raw CSS color
 * string, or a `theme` map keyed by light/dark for theme-scoped values
 * generated by {@link ChartStyle}.
 */
type ChartConfig = {
  [k in string]: {
    label?: React.ReactNode;
    icon?: React.ComponentType;
  } & (
    | { color?: ChartColorKeys; theme?: never }
    | { color?: never; theme: Record<keyof typeof THEMES, string> }
  );
};

/**
 * The five themeable chart color tokens, mapped to their CSS custom
 * properties. Use these keys in {@link ChartConfig} `color` fields to stay
 * on-palette in both light and dark modes.
 */
const CHART_COLORS = {
  "chart-1": "var(--chart-1)",
  "chart-2": "var(--chart-2)",
  "chart-3": "var(--chart-3)",
  "chart-4": "var(--chart-4)",
  "chart-5": "var(--chart-5)",
} as const;

type ChartColorKeys = keyof typeof CHART_COLORS | (string & {});

/** Default color cycle applied to series when none is specified. */
const DEFAULT_COLORS = [
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
] as const;

type ChartContextProps = {
  config: ChartConfig;
  data?: ChartDatum[];
  layout: ChartLayout;
  dataKey?: string;
  /** The series currently isolated by the interactive legend, or `null`. */
  selectedLegend: string | null;
  /** Sets (or clears, with `null`) the isolated legend series. */
  onLegendSelect: (legendItem: string | null) => void;
};

const ChartContext = createContext<ChartContextProps | null>(null);

/**
 * Reads the nearest {@link Chart} / {@link ChartContainer} context.
 *
 * Used by the layout-aware {@link XAxis}, {@link YAxis},
 * {@link CartesianGrid}, the {@link ChartTooltipContent}, and the
 * interactive {@link ChartLegendContent}.
 */
export function useChart() {
  const context = use(ChartContext);

  if (!context) {
    throw new Error("useChart must be used within a <Chart />");
  }

  return context;
}

// #region Helpers ----------------------------------------------------------

/** Formats a 0–1 ratio as an integer percentage string (e.g. `0.42` → `"42%"`). */
export function valueToPercent(value: number) {
  return `${(value * 100).toFixed(0)}%`;
}

/**
 * Minimal controlled/uncontrolled state hook. When `value` is provided the
 * state is controlled (the setter only forwards to `onChange`); otherwise it
 * falls back to internal state seeded from `defaultValue`. A `value` of `null`
 * still counts as controlled — only `undefined` selects uncontrolled mode.
 */
function useControllableState<T>({
  value,
  defaultValue,
  onChange,
}: {
  value?: T;
  defaultValue: T;
  onChange?: (next: T) => void;
}): [T, (next: T) => void] {
  const isControlled = value !== undefined;
  const [uncontrolled, setUncontrolled] = useState<T>(defaultValue);
  const resolved = value === undefined ? uncontrolled : value;

  const setValue = useCallback(
    (next: T) => {
      if (!isControlled) {
        setUncontrolled(next);
      }
      onChange?.(next);
    },
    [isControlled, onChange]
  );

  return [resolved, setValue];
}

/**
 * Builds a `category → color key` map, cycling through `colors` so charts
 * with more series than colors wrap around the palette.
 */
const constructCategoryColors = (
  categories: string[],
  colors: readonly ChartColorKeys[]
): Map<string, ChartColorKeys> => {
  const categoryColors = new Map<string, ChartColorKeys>();

  let index = 0;
  for (const category of categories) {
    const color = colors[index % colors.length];
    if (color !== undefined) {
      categoryColors.set(category, color);
    }
    index += 1;
  }

  return categoryColors;
};

/**
 * Resolves a color source to a concrete CSS value: built-in token keys map
 * to their `var(--chart-N)`, raw strings pass through, and `undefined`
 * falls back to the first chart color.
 */
const getColorValue = (color?: string): string => {
  if (!color) {
    return "var(--chart-1)";
  }

  return CHART_COLORS[color as keyof typeof CHART_COLORS] ?? color;
};

/**
 * Resolves the {@link ChartConfig} entry for a recharts tooltip/legend
 * payload item, walking both the top-level payload and recharts' nested
 * `payload.payload` data row before falling back to the literal key.
 */
function getPayloadConfigFromPayload(
  config: ChartConfig,
  payload: unknown,
  key: string
) {
  if (typeof payload !== "object" || payload === null) {
    return;
  }

  const payloadPayload =
    "payload" in payload &&
    typeof payload.payload === "object" &&
    payload.payload !== null
      ? payload.payload
      : undefined;

  let configLabelKey: string = key;

  if (
    key in payload &&
    typeof payload[key as keyof typeof payload] === "string"
  ) {
    configLabelKey = payload[key as keyof typeof payload] as string;
  } else if (
    payloadPayload &&
    key in payloadPayload &&
    typeof payloadPayload[key as keyof typeof payloadPayload] === "string"
  ) {
    configLabelKey = payloadPayload[
      key as keyof typeof payloadPayload
    ] as string;
  }

  return configLabelKey in config
    ? config[configLabelKey]
    : config[key as keyof typeof config];
}

// #region Root -------------------------------------------------------------

/**
 * Shared props consumed by the cartesian chart wrappers
 * ({@link AreaChart}, {@link BarChart}, {@link LineChart}).
 */
interface BaseChartProps extends React.ComponentProps<"div"> {
  /** Props forwarded to the recharts `CartesianGrid` element. */
  cartesianGridProps?: CartesianGridProps;
  /** Ordered palette; cycles when shorter than the number of series. */
  colors?: readonly ChartColorKeys[];
  /** Per-series {@link ChartConfig}; series are derived from its keys. */
  config: ChartConfig;
  /** Pixel height of the chart canvas. Defaults to 200 (mobile) / 370. */
  containerHeight?: number;
  /** Array of data rows. */
  data: ChartDatum[];
  /** Field used for the category axis labels. */
  dataKey: string;
  /** Uncontrolled initial selected series. Defaults to `null`. */
  defaultSelectedSeries?: string | null;

  /** Render only the first and last X-axis labels. */
  displayEdgeLabelsOnly?: boolean;
  /** Axis tick interval strategy. */
  intervalType?: IntervalType;
  /** Chart orientation — see {@link ChartLayout}. */
  layout?: ChartLayout;

  /** `true` for the default interactive legend, or custom recharts content. */
  legend?: LegendContentType | boolean;
  /** Extra props forwarded to the recharts `Legend` element. */
  legendProps?: Omit<
    React.ComponentProps<typeof LegendPrimitive>,
    "content" | "ref"
  >;
  /** Fires when the selection changes (legend click, bar click, or selector). */
  onSelectedSeriesChange?: (value: string | null) => void;

  /**
   * Controlled selected series (the isolated/highlighted one, or `null`).
   * Share this with a {@link ChartSeriesSelector} `value` so a header
   * selector and the in-chart interactive legend stay in sync.
   */
  selectedSeries?: string | null;

  /** Shows the {@link CartesianGrid} when `true`. */
  showGridLines?: boolean;
  /** Shows the {@link XAxis} when `true`. */
  showXAxis?: boolean;
  /** Shows the {@link YAxis} when `true`. */
  showYAxis?: boolean;

  /** `true` for the default styled tooltip, or a custom recharts content. */
  tooltip?: TooltipContentType<ValueType, NameType> | boolean;
  /** Extra props forwarded to the recharts `Tooltip` element. */
  tooltipProps?: Omit<TooltipProps, "content"> & {
    showLabel?: boolean;
    labelSeparator?: boolean;
    showIndicator?: boolean;
    indicator?: "line" | "dot" | "dashed";
    nameKey?: string;
    labelKey?: string;
  };
  /** Stacking behaviour — see {@link ChartType}. */
  type?: ChartType;
  /** Formats numeric value-axis ticks and tooltip values. */
  valueFormatter?: (value: number) => string;

  /** Extra props forwarded to the recharts `XAxis` element. */
  xAxisProps?: XAxisPrimitiveProps;
  /** Extra props forwarded to the recharts `YAxis` element. */
  yAxisProps?: YAxisPrimitiveProps;
}

const THEMES = { light: "", dark: ".dark" } as const;

/**
 * Reset classes applied to every chart root that neutralise recharts'
 * hard-coded colors/outlines and re-map them onto our design tokens.
 */
const chartRootClassName = cn(
  "z-20 flex w-full justify-center text-xs",
  "[&_.recharts-cartesian-axis-tick_text]:fill-muted-foreground [&_.recharts-cartesian-grid_line[stroke='#ccc']]:stroke-border/80 [&_.recharts-curve.recharts-tooltip-cursor]:stroke-border [&_.recharts-layer]:outline-hidden [&_.recharts-polar-grid_[stroke='#ccc']]:stroke-border [&_.recharts-radial-bar-background-sector]:fill-muted [&_.recharts-rectangle.recharts-tooltip-cursor]:fill-muted [&_.recharts-reference-line_[stroke='#ccc']]:stroke-border [&_.recharts-sector[stroke='#fff']]:stroke-transparent [&_.recharts-sector]:outline-hidden [&_.recharts-surface]:outline-hidden",
  "[&_.recharts-dot[fill='#fff']]:fill-(--line-color)",
  "[&_.recharts-active-dot>.recharts-dot]:stroke-foreground/10"
);

/**
 * Root wrapper for the data-driven chart components.
 *
 * Provides the {@link ChartConfig}, data, layout, and interactive-legend
 * state to descendants via context, injects per-series `--color-<key>` CSS
 * variables through {@link ChartStyle}, and renders a recharts
 * `ResponsiveContainer`. `children` may be a single recharts element or a
 * render-prop receiving the chart context (used by the wrappers to read
 * `selectedLegend` / `onLegendSelect`).
 *
 * @remarks
 * - Prefer the high-level wrappers ({@link AreaChart}, {@link BarChart},
 *   {@link LineChart}, {@link PieChart}); reach for `Chart` directly only
 *   when composing custom recharts series.
 * - For the simpler shadcn-style primitive (config context without the
 *   interactive legend / data requirement) use {@link ChartContainer}.
 *
 * @example
 * ```tsx
 * <Chart config={config} data={data} dataKey="month">
 *   {() => (
 *     <BarChartPrimitive data={data}>
 *       <XAxis />
 *       <YAxis />
 *       <Bar dataKey="revenue" />
 *     </BarChartPrimitive>
 *   )}
 * </Chart>
 * ```
 */
const Chart = ({
  id,
  className,
  children,
  config,
  data,
  dataKey,
  ref,
  layout = "horizontal",
  containerHeight,
  selectedSeries,
  defaultSelectedSeries = null,
  onSelectedSeriesChange,
  ...props
}: Omit<React.ComponentProps<"div">, "children"> &
  Pick<ChartContextProps, "data" | "dataKey"> & {
    config: ChartConfig;
    containerHeight?: number;
    layout?: ChartLayout;
    selectedSeries?: string | null;
    defaultSelectedSeries?: string | null;
    onSelectedSeriesChange?: (value: string | null) => void;
    children: ReactElement | ((props: ChartContextProps) => ReactElement);
  }) => {
  const isMobile = useIsMobile();
  const uniqueId = useId();
  const chartId = useMemo(
    () => `chart-${id || uniqueId.replace(/:/g, "")}`,
    [id, uniqueId]
  );

  const [selectedLegend, onLegendSelect] = useControllableState<string | null>({
    value: selectedSeries,
    defaultValue: defaultSelectedSeries ?? null,
    onChange: onSelectedSeriesChange,
  });

  const value = useMemo<ChartContextProps>(
    () => ({
      config,
      selectedLegend,
      onLegendSelect,
      data: data ?? [],
      dataKey: dataKey ?? "value",
      layout,
    }),
    [config, selectedLegend, onLegendSelect, data, dataKey, layout]
  );

  return (
    <ChartContext value={value}>
      <div
        className={cn(chartRootClassName, className)}
        data-chart={chartId}
        data-slot="chart"
        ref={ref}
        {...props}
      >
        <ChartStyle config={config} id={chartId} />
        <ResponsiveContainer height={containerHeight ?? (isMobile ? 200 : 370)}>
          {typeof children === "function" ? children(value) : children}
        </ResponsiveContainer>
      </div>
    </ChartContext>
  );
};

const noop = () => {
  // intentionally empty — default legend handler for ChartContainer
};

/**
 * Lightweight chart root that only supplies the {@link ChartConfig} context
 * (plus a no-op legend state) and a `ResponsiveContainer`.
 *
 * Use this when you want to compose recharts primitives by hand without the
 * data-driven {@link Chart} wrapper. The {@link ChartTooltipContent} and
 * {@link ChartLegendContent} bodies work inside either root.
 *
 * @example
 * ```tsx
 * <ChartContainer config={config} className="aspect-video">
 *   <BarChartPrimitive data={data}>
 *     <Bar dataKey="revenue" fill="var(--color-revenue)" />
 *   </BarChartPrimitive>
 * </ChartContainer>
 * ```
 */
function ChartContainer({
  id,
  className,
  children,
  config,
  ...props
}: React.ComponentProps<"div"> & {
  config: ChartConfig;
  children: React.ComponentProps<typeof ResponsiveContainer>["children"];
}) {
  const uniqueId = useId();
  const chartId = `chart-${id || uniqueId.replace(/:/g, "")}`;

  const value = useMemo<ChartContextProps>(
    () => ({
      config,
      selectedLegend: null,
      onLegendSelect: noop,
      data: [],
      dataKey: "value",
      layout: "horizontal",
    }),
    [config]
  );

  return (
    <ChartContext value={value}>
      <div
        className={cn(
          "aspect-video [&_.recharts-cartesian-axis-tick_text]:fill-muted-foreground [&_.recharts-cartesian-grid_line[stroke='#ccc']]:stroke-border/50",
          chartRootClassName,
          className
        )}
        data-chart={chartId}
        data-slot="chart"
        {...props}
      >
        <ChartStyle config={config} id={chartId} />
        <ResponsiveContainer>{children}</ResponsiveContainer>
      </div>
    </ChartContext>
  );
}

/**
 * Injects a scoped `<style>` declaring `--color-<key>` custom properties for
 * each series under `[data-chart=<id>]`, for both light and dark themes.
 * Entries without a `color` or `theme` are skipped. Called internally by
 * {@link Chart} and {@link ChartContainer}.
 */
const ChartStyle = ({ id, config }: { id: string; config: ChartConfig }) => {
  const colorConfig = Object.entries(config).filter(
    ([, conf]) => conf.theme || conf.color
  );

  if (!colorConfig.length) {
    return null;
  }

  return (
    <style
      // biome-ignore lint/security/noDangerouslySetInnerHtml: static chart-theme CSS derived from build-time ChartConfig, no user input
      dangerouslySetInnerHTML={{
        __html: Object.entries(THEMES)
          .map(
            ([theme, prefix]) => `
${prefix} [data-chart=${id}] {
${colorConfig
  .map(([key, itemConfig]) => {
    const themed = itemConfig.theme?.[theme as keyof typeof itemConfig.theme];
    const color = getColorValue(themed || itemConfig.color);
    return color ? `  --color-${key}: ${color};` : null;
  })
  .join("\n")}
}
`
          )
          .join("\n"),
      }}
    />
  );
};

// #region Tooltip & cursor -------------------------------------------------

/** Props for {@link ChartTooltip}. */
type ChartTooltipProps = TooltipProps<ValueType, NameType>;

const tooltipWrapperStyle = { outline: "none" } as const;

const cursorStyleRadial = {
  stroke: "var(--muted)",
  strokeWidth: 0.1,
  fill: "var(--muted)",
  fillOpacity: 0.5,
} as const;

const cursorStyleDefault = {
  stroke: "var(--muted)",
  strokeWidth: 1,
  fill: "var(--muted)",
  fillOpacity: 0.5,
} as const;

/**
 * Recharts `Tooltip` pre-wired with a token-driven cursor that adapts to the
 * chart layout (radial vs. cartesian). Pair with {@link ChartTooltipContent}.
 */
const ChartTooltip = (props: TooltipProps) => {
  const { layout } = useChart();
  const cursorStyle =
    layout === "radial" ? cursorStyleRadial : cursorStyleDefault;

  return (
    <TooltipPrimitive
      cursor={cursorStyle}
      wrapperStyle={tooltipWrapperStyle}
      {...props}
    />
  );
};

/** Props for {@link ChartLegend}. */
type ChartLegendProps = Omit<
  React.ComponentProps<typeof LegendPrimitive>,
  "ref"
>;

/** Recharts `Legend` defaulted to center/bottom. Pair with {@link ChartLegendContent}. */
const ChartLegend = (props: ChartLegendProps) => (
  <LegendPrimitive align="center" verticalAlign="bottom" {...props} />
);

// #region Axes & grid ------------------------------------------------------

/** Props for {@link XAxis}. */
interface XAxisProps extends Omit<XAxisPrimitiveProps, "ref"> {
  /** Render only the first and last tick labels, hiding all intermediate ones. */
  displayEdgeLabelsOnly?: boolean;
  /** Recharts tick interval strategy forwarded to the `XAxis` primitive. */
  intervalType?: IntervalType;
}

const tickHorizontal = { transform: "translate(32, 6)" } as const;

/**
 * Layout-aware recharts `XAxis`. Reads `dataKey`/`data`/`layout` from the
 * chart context, hides its line/border, and supports edge-only labels.
 */
const XAxis = ({
  displayEdgeLabelsOnly,
  className,
  intervalType = "preserveStartEnd",
  minTickGap = 5,
  type,
  ...props
}: XAxisProps) => {
  const { dataKey, data, layout } = useChart();

  // In a vertical layout the X axis carries the numeric values, so it must be
  // a number axis with no category dataKey. Defaulting to category here (the
  // recharts default) produces NaN ticks because there is no category source.
  const isVertical = layout === "vertical";

  const ticks =
    displayEdgeLabelsOnly && data?.length && dataKey
      ? [data[0]?.[dataKey], data.at(-1)?.[dataKey]]
      : undefined;

  const tick = layout === "horizontal" ? tickHorizontal : undefined;

  return (
    <XAxisPrimitive
      axisLine={false}
      className={cn(
        "text-muted-foreground text-xs **:[text]:fill-muted-foreground",
        className
      )}
      dataKey={layout === "horizontal" ? dataKey : undefined}
      interval={displayEdgeLabelsOnly ? "preserveStartEnd" : intervalType}
      minTickGap={minTickGap}
      tick={tick as XAxisPrimitiveProps["tick"]}
      tickLine={false}
      ticks={ticks as XAxisPrimitiveProps["ticks"]}
      type={type ?? (isVertical ? "number" : "category")}
      {...props}
    />
  );
};

const yAxisTickHorizontal = { transform: "translate(-3, 0)" } as const;
const yAxisTickVertical = { transform: "translate(0, 0)" } as const;

/**
 * Layout-aware recharts `YAxis`. Swaps category/number roles and tick
 * placement based on the chart `layout` from context.
 */
const YAxis = ({
  className,
  width,
  domain = ["auto", "auto"],
  type,
  ...props
}: Omit<YAxisPrimitiveProps, "ref">) => {
  const { layout, dataKey } = useChart();

  const isHorizontal = layout === "horizontal";
  const tick = isHorizontal ? yAxisTickHorizontal : yAxisTickVertical;
  const computedWidth = width ?? (isHorizontal ? 40 : 80);
  const axisType = type ?? (isHorizontal ? "number" : "category");

  return (
    <YAxisPrimitive
      axisLine={false}
      className={cn(
        "text-muted-foreground text-xs **:[text]:fill-muted-foreground",
        className
      )}
      dataKey={isHorizontal ? undefined : dataKey}
      domain={domain}
      interval={isHorizontal ? undefined : "equidistantPreserveStart"}
      tick={tick}
      tickLine={false}
      type={axisType}
      width={computedWidth}
      {...props}
    />
  );
};

/** Layout-aware recharts `CartesianGrid` drawing only the relevant axis lines. */
const CartesianGrid = ({ className, ...props }: CartesianGridProps) => {
  const { layout } = useChart();
  return (
    <CartesianGridPrimitive
      className={cn("stroke-1 stroke-muted", className)}
      horizontal={layout !== "vertical"}
      vertical={layout === "vertical"}
      {...props}
    />
  );
};

// #region Tooltip content --------------------------------------------------

type ChartTooltipContentExtras = {
  showLabel?: boolean;
  labelSeparator?: boolean;
  showIndicator?: boolean;
  indicator?: "line" | "dot" | "dashed";
  nameKey?: string;
  labelKey?: string;
};

/**
 * Frosted-glass tooltip body rendered inside `<ChartTooltip content={…} />`.
 *
 * Reads series labels/colors from the enclosing chart config and supports
 * three indicator styles (`dot`, `line`, `dashed`), an optional label
 * separator, label suppression, and a custom `formatter` override.
 *
 * @remarks
 * - When a single payload entry is present with a non-`dot` indicator the
 *   label is nested inline beside the value.
 * - Pass `nameKey` / `labelKey` to resolve config entries by a field other
 *   than the recharts-inferred one.
 */
const ChartTooltipContent = <TValue extends ValueType, TName extends NameType>({
  payload,
  className,
  indicator = "dot",
  showLabel = true,
  showIndicator = true,
  label,
  labelSeparator = true,
  labelFormatter,
  labelClassName,
  formatter,
  color,
  nameKey,
  labelKey,
  ref,
}: TooltipContentProps<TValue, TName> &
  React.ComponentProps<"div"> &
  ChartTooltipContentExtras) => {
  const { config } = useChart();

  const tooltipLabel = useMemo(() => {
    if (!(showLabel && payload?.length)) {
      return null;
    }

    const [item] = payload;
    if (!item) {
      return null;
    }

    const key = `${labelKey || item.dataKey || item.name || "value"}`;
    const itemConfig = getPayloadConfigFromPayload(config, item, key);
    const value =
      !labelKey && typeof label === "string"
        ? config[label]?.label || label
        : itemConfig?.label;

    if (labelFormatter) {
      return (
        <div className={labelClassName}>{labelFormatter(value, payload)}</div>
      );
    }

    if (!value) {
      return null;
    }

    return <div className={labelClassName}>{value}</div>;
  }, [
    label,
    labelFormatter,
    payload,
    showLabel,
    labelClassName,
    config,
    labelKey,
  ]);

  if (!payload?.length) {
    return null;
  }

  const nestLabel = payload.length === 1 && indicator !== "dot";

  return (
    <div
      className={cn(
        "grid min-w-48 items-start rounded-lg bg-popover/70 p-3 py-2 text-popover-foreground text-xs shadow-md ring-1 ring-foreground/10 backdrop-blur-lg",
        className
      )}
      ref={ref}
    >
      {showLabel ? (
        <>
          {nestLabel ? null : (
            <span className="font-medium">{tooltipLabel}</span>
          )}
          {labelSeparator && (
            <span
              aria-hidden
              className="mt-2 mb-3 block h-px w-full bg-border/70"
            />
          )}
        </>
      ) : null}
      <div className="grid gap-3">
        {payload.map((item, index) => {
          const key = `${nameKey || item.name || item.dataKey || "value"}`;
          const itemConfig = getPayloadConfigFromPayload(config, item, key);
          const indicatorColor = color || item.payload?.fill || item.color;

          return (
            <div
              className={cn(
                "flex w-full flex-wrap items-stretch gap-2 *:[svg]:text-muted-foreground",
                indicator === "dot" && "items-center *:[svg]:size-2.5",
                indicator === "line" && "*:[svg]:h-full *:[svg]:w-2.5"
              )}
              key={key}
            >
              {formatter && item?.value !== undefined && item.name ? (
                formatter(item.value, item.name, item, index, item.payload)
              ) : (
                <>
                  {renderIndicator({
                    itemConfig,
                    hideIndicator: !showIndicator,
                    indicator,
                    nestLabel,
                    indicatorColor,
                  })}
                  <div
                    className={cn(
                      "flex flex-1 justify-between leading-none",
                      nestLabel ? "items-end" : "items-center"
                    )}
                  >
                    <div className="grid gap-1.5">
                      {nestLabel ? tooltipLabel : null}
                      <span className="text-muted-foreground">
                        {itemConfig?.label || item.name}
                      </span>
                    </div>
                    {item.value !== undefined && item.value !== null && (
                      <span className="font-medium font-mono text-foreground tabular-nums">
                        {item.value.toLocaleString()}
                      </span>
                    )}
                  </div>
                </>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};

/** Renders the colored dot/line/dashed marker (or config icon) for a tooltip row. */
function renderIndicator({
  itemConfig,
  hideIndicator,
  indicator,
  nestLabel,
  indicatorColor,
}: {
  itemConfig: ReturnType<typeof getPayloadConfigFromPayload>;
  hideIndicator: boolean;
  indicator: "line" | "dot" | "dashed";
  nestLabel: boolean;
  indicatorColor?: string;
}) {
  if (itemConfig?.icon) {
    return <itemConfig.icon />;
  }

  if (hideIndicator) {
    return null;
  }

  return (
    <div
      className={cn(
        "shrink-0 rounded-full border-(--color-border) bg-(--color-bg)",
        indicator === "dot" && "size-2.5",
        indicator === "line" && "w-1",
        indicator === "dashed" &&
          "w-0 border-[1.5px] border-dashed bg-transparent",
        nestLabel && indicator === "dashed" && "my-0.5"
      )}
      style={
        {
          "--color-bg": indicatorColor,
          "--color-border": indicatorColor,
        } as React.CSSProperties
      }
    />
  );
}

// #region Legend content ---------------------------------------------------

/** Props for {@link ChartLegendContent}. */
type ChartLegendContentProps = React.ComponentProps<"div"> &
  Pick<LegendProps, "align" | "verticalAlign"> & {
    /** Recharts legend payload injected automatically by the `Legend` wrapper. */
    payload?: readonly LegendPayload[];
    /** When `true`, shows the color icon/dot for each legend entry. */
    showIcon?: boolean;
    /** Data key used to look up the series label in {@link ChartConfig}. */
    nameKey?: string;
  };

const legendJustify = {
  right: "justify-end",
  left: "justify-start",
  center: "justify-center",
} as const;

/**
 * Interactive legend body rendered inside `<ChartLegend content={…} />`.
 *
 * Each entry is a toggle button: clicking isolates that series (dimming the
 * rest); clicking it again clears the selection. State lives in the chart
 * context (`selectedLegend` / `onLegendSelect`) so the series rendering can
 * react to it.
 */
const ChartLegendContent = ({
  className,
  showIcon = true,
  payload,
  align = "right",
  verticalAlign = "bottom",
  nameKey,
}: ChartLegendContentProps) => {
  const { config, selectedLegend, onLegendSelect } = useChart();

  if (!payload?.length) {
    return null;
  }

  return (
    <div
      className={cn(
        "flex flex-wrap items-center gap-x-1",
        verticalAlign === "top" ? "pb-3" : "pt-3",
        legendJustify[align ?? "right"],
        className
      )}
    >
      {payload.map((item) => {
        const key = `${nameKey || item.dataKey || "value"}`;
        const itemConfig = getPayloadConfigFromPayload(config, item, key);
        const selected = selectedLegend === key;

        return (
          <button
            aria-pressed={selected}
            className={cn(
              "flex items-center gap-2 rounded-sm px-2 py-1 text-muted-foreground *:[svg]:-mx-0.5 *:[svg]:size-2.5 *:[svg]:shrink-0 *:[svg]:text-muted-foreground",
              "hover:bg-secondary/70 hover:text-secondary-foreground focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50",
              selected && "bg-secondary/70 text-secondary-foreground"
            )}
            key={key}
            onClick={(event) => {
              // Recharts renders the legend inside the chart wrapper, which
              // carries the chart-level onClick that clears the selection.
              // Stop the bubble so the toggle isn't immediately undone.
              event.stopPropagation();
              onLegendSelect(selected ? null : key);
            }}
            type="button"
          >
            {itemConfig?.icon && showIcon ? (
              <itemConfig.icon />
            ) : (
              <div
                className="size-2.5 rounded-full"
                style={{ backgroundColor: item.color }}
              />
            )}
            {itemConfig?.label}
          </button>
        );
      })}
    </div>
  );
};

// #region Series selector --------------------------------------------------

/** Props for {@link ChartSeriesSelector}. */
interface ChartSeriesSelectorProps
  extends Omit<React.ComponentProps<"div">, "onChange" | "defaultValue"> {
  /** Clicking the active series clears the selection. Defaults to `true`. */
  allowDeselect?: boolean;
  /** Palette for the color dots; cycles when shorter than the series count. */
  colors?: readonly ChartColorKeys[];
  /** Per-series {@link ChartConfig}; one toggle is rendered per key. */
  config: ChartConfig;
  /** Data rows used to compute each series' total when `showTotal`. */
  data?: ChartDatum[];
  /** Uncontrolled initial selection. Defaults to `null`. */
  defaultValue?: string | null;
  /** Fires with the new selection (or `null` when cleared). */
  onValueChange?: (value: string | null) => void;
  /** Restrict and order the rendered series. Defaults to `Object.keys(config)`. */
  series?: string[];
  /** Render each series' summed total beneath its label (dashboard style). */
  showTotal?: boolean;
  /** Controlled selected series key, or `null` for none. */
  value?: string | null;
  /** Formats the per-series total. Defaults to `toLocaleString`. */
  valueFormatter?: (value: number) => string;
}

const defaultTotalFormatter = (value: number) => value.toLocaleString();

/** Sums a numeric `key` across `data`, ignoring non-numeric cells. */
function sumSeries(data: ChartDatum[] | undefined, key: string): number {
  if (!data) {
    return 0;
  }

  let total = 0;
  for (const row of data) {
    const cell = row[key];
    if (typeof cell === "number") {
      total += cell;
    }
  }

  return total;
}

/**
 * Header-mounted metric selector for the chart family.
 *
 * Renders one toggle per `config` series — a color dot + label, plus an
 * optional summed total — driving a single "selected series" value. Pair it
 * with a chart by sharing state: feed the same `value` to the chart's
 * `selectedSeries`, and update from both this `onValueChange` and the chart's
 * `onSelectedSeriesChange`, so the header toggles and the in-chart interactive
 * legend stay in lockstep (clicking a series isolates it; clicking it again
 * clears).
 *
 * Controlled (`value` + `onValueChange`) or uncontrolled (`defaultValue`).
 *
 * @example
 * ```tsx
 * const [series, setSeries] = useState<string | null>("revenue");
 * return (
 *   <>
 *     <ChartSeriesSelector
 *       config={config}
 *       data={data}
 *       onValueChange={setSeries}
 *       showTotal
 *       value={series}
 *     />
 *     <BarChart
 *       config={config}
 *       data={data}
 *       dataKey="month"
 *       onSelectedSeriesChange={setSeries}
 *       selectedSeries={series}
 *     />
 *   </>
 * );
 * ```
 */
function ChartSeriesSelector({
  config,
  series,
  value,
  defaultValue = null,
  onValueChange,
  colors = DEFAULT_COLORS,
  data,
  valueFormatter = defaultTotalFormatter,
  showTotal = false,
  allowDeselect = true,
  className,
  ...props
}: ChartSeriesSelectorProps) {
  const keys = series ?? Object.keys(config);
  const categoryColors = constructCategoryColors(keys, colors);
  const [selected, setSelected] = useControllableState<string | null>({
    value,
    defaultValue,
    onChange: onValueChange,
  });

  return (
    <div
      className={cn(
        showTotal
          ? "flex flex-wrap items-stretch gap-2"
          : "flex flex-wrap items-center gap-1.5",
        className
      )}
      data-slot="chart-series-selector"
      role="toolbar"
      {...props}
    >
      {keys.map((key) => {
        const itemConfig = config[key];
        const isActive = selected === key;
        const color = getColorValue(
          itemConfig?.color || categoryColors.get(key)
        );
        const label = itemConfig?.label ?? key;
        const handleClick = () =>
          setSelected(isActive && allowDeselect ? null : key);

        if (showTotal) {
          return (
            <button
              aria-pressed={isActive}
              className={cn(
                "flex flex-1 flex-col gap-1 rounded-lg border px-3 py-2 text-left transition-colors hover:bg-secondary/50 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50",
                isActive
                  ? "border-foreground/20 bg-secondary/60"
                  : "border-transparent bg-secondary/20"
              )}
              data-active={isActive}
              data-slot="chart-series-selector-item"
              key={key}
              onClick={handleClick}
              type="button"
            >
              <span className="flex items-center gap-1.5 text-muted-foreground text-xs">
                <span
                  aria-hidden
                  className="size-2 shrink-0 rounded-full"
                  style={{ backgroundColor: color }}
                />
                {label}
              </span>
              <span className="font-medium font-mono text-foreground text-lg tabular-nums">
                {valueFormatter(sumSeries(data, key))}
              </span>
            </button>
          );
        }

        return (
          <button
            aria-pressed={isActive}
            className={cn(
              "flex items-center gap-1.5 rounded-sm px-2 py-1 text-muted-foreground text-xs transition-colors hover:bg-secondary/70 hover:text-secondary-foreground focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50",
              isActive && "bg-secondary/70 text-secondary-foreground"
            )}
            data-active={isActive}
            data-slot="chart-series-selector-item"
            key={key}
            onClick={handleClick}
            type="button"
          >
            <span
              aria-hidden
              className="size-2.5 shrink-0 rounded-full"
              style={{ backgroundColor: color }}
            />
            {label}
          </button>
        );
      })}
    </div>
  );
}

export type {
  BaseChartProps,
  ChartColorKeys,
  ChartConfig,
  ChartDatum,
  ChartLayout,
  ChartLegendContentProps,
  ChartLegendProps,
  ChartSeriesSelectorProps,
  ChartTooltipProps,
  ChartType,
  IntervalType,
  XAxisProps,
};
export {
  CartesianGrid,
  CHART_COLORS,
  Chart,
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartSeriesSelector,
  ChartStyle,
  ChartTooltip,
  ChartTooltipContent,
  constructCategoryColors,
  DEFAULT_COLORS,
  getColorValue,
  getPayloadConfigFromPayload,
  XAxis,
  YAxis,
};
