"use client";

import { mergeProps } from "@base-ui/react/merge-props";
import { useRender } from "@base-ui/react/use-render";
import type * as React from "react";
import { createContext, useContext, useId } from "react";
import {
  Controller,
  type ControllerProps,
  type FieldPath,
  type FieldValues,
  FormProvider,
  useFormContext,
} from "react-hook-form";

import { cn } from "../utils/index";
import { Label } from "./label";

/**
 * Root provider for a react-hook-form managed form.
 *
 * Re-exported directly from react-hook-form's `FormProvider`. Pass the
 * object returned by `useForm()` as spread props so that all descendant
 * {@link FormField} and {@link useFormField} calls can access the form
 * context.
 *
 * @example
 * ```tsx
 * const form = useForm<Schema>();
 * return (
 *   <Form {...form}>
 *     <form onSubmit={form.handleSubmit(onSubmit)}>…</form>
 *   </Form>
 * );
 * ```
 */
const Form = FormProvider;

/**
 * Internal context value carried by each {@link FormField} to its
 * descendants so {@link useFormField} can resolve the field name.
 */
type FormFieldContextValue<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
> = {
  name: TName;
};

// Private context — not exported; consumers use useFormField instead.
const FormFieldContext = createContext<FormFieldContextValue>(
  {} as FormFieldContextValue
);

/**
 * Connects a single react-hook-form field to the design-system form
 * components.
 *
 * Wraps react-hook-form's `<Controller>` and publishes the field's `name`
 * via a React context so {@link useFormField} (and every sub-component that
 * calls it) can read validation state without prop drilling.
 *
 * @remarks
 * Every field in a {@link Form} should be wrapped in a `FormField`. The
 * `render` prop receives `{ field, fieldState }` and should render the
 * control inside {@link FormItem} → {@link FormControl} for full
 * accessibility wiring.
 *
 * @example
 * ```tsx
 * <FormField
 *   control={form.control}
 *   name="email"
 *   render={({ field }) => (
 *     <FormItem>
 *       <FormLabel>Email</FormLabel>
 *       <FormControl render={<Input type="email" {...field} />} />
 *       <FormMessage />
 *     </FormItem>
 *   )}
 * />
 * ```
 */
function FormField<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
>({ ...props }: ControllerProps<TFieldValues, TName>) {
  return (
    <FormFieldContext.Provider value={{ name: props.name }}>
      <Controller {...props} />
    </FormFieldContext.Provider>
  );
}

/**
 * Hook that returns the current field's metadata and validation state.
 *
 * Must be called inside a component rendered within {@link FormField}.
 * Returns `id`, `name`, `formItemId`, `formDescriptionId`,
 * `formMessageId`, plus all react-hook-form `fieldState` properties
 * (`error`, `invalid`, `isDirty`, etc.).
 *
 * @throws when called outside a {@link FormField} context.
 */
const useFormField = () => {
  const fieldContext = useContext(FormFieldContext);
  const itemContext = useContext(FormItemContext);
  const { getFieldState, formState } = useFormContext();

  const fieldState = getFieldState(fieldContext.name, formState);

  if (!fieldContext) {
    throw new Error("useFormField should be used within <FormField>");
  }

  const { id } = itemContext;

  return {
    id,
    name: fieldContext.name,
    // Stable IDs for htmlFor / aria-describedby / aria-errormessage
    formItemId: `${id}-form-item`,
    formDescriptionId: `${id}-form-item-description`,
    formMessageId: `${id}-form-item-message`,
    ...fieldState,
  };
};

/**
 * Internal context value generated by {@link FormItem} so that sibling
 * sub-components share a stable auto-generated ID prefix.
 */
type FormItemContextValue = {
  id: string;
};

// Private context — exposes the shared ID to FormLabel/Control/etc.
const FormItemContext = createContext<FormItemContextValue>(
  {} as FormItemContextValue
);

/**
 * Layout wrapper for a single form field row.
 *
 * Generates a stable `id` prefix (via `useId`) and shares it through
 * context so {@link FormLabel}, {@link FormControl}, {@link FormDescription},
 * and {@link FormMessage} can wire up matching `htmlFor` /
 * `aria-describedby` attributes without manual IDs.
 *
 * @remarks
 * Always nest `FormItem` inside {@link FormField}. Place
 * {@link FormLabel}, {@link FormControl}, {@link FormDescription}, and
 * {@link FormMessage} as direct children in that order.
 */
function FormItem({ className, ...props }: React.ComponentProps<"div">) {
  // useId ensures a stable, collision-free prefix for all sibling IDs.
  const id = useId();

  return (
    <FormItemContext.Provider value={{ id }}>
      <div
        className={cn("flex flex-col gap-2", className)}
        data-slot="form-item"
        {...props}
      />
    </FormItemContext.Provider>
  );
}

/**
 * Label for a react-hook-form controlled field inside {@link FormItem}.
 *
 * Automatically sets `htmlFor` to the matching {@link FormControl} `id`
 * and turns destructive red when the field has a validation error.
 *
 * @remarks
 * Pass `required` to render a small red asterisk after the label text.
 */
function FormLabel({
  className,
  required,
  children,
  ...props
}: React.ComponentProps<"label"> & { required?: boolean }) {
  const { error, formItemId } = useFormField();

  return (
    <Label
      // Turn label red when the field is in an error state
      className={cn(error ? "text-destructive" : null, className)}
      data-slot="form-label"
      htmlFor={formItemId}
      {...props}
    >
      {children}
      {required ? <span className="ml-0.5 text-destructive">*</span> : null}
    </Label>
  );
}

/**
 * Accessibility wrapper that binds a form control to its label, description,
 * and error message via ARIA attributes.
 *
 * Uses Base UI's `useRender` so the `render` prop can project the behavior
 * onto any element (e.g. `render={<Input />}`). The wrapper sets
 * `id`, `aria-invalid`, and `aria-describedby` automatically from the
 * enclosing {@link FormField} / {@link FormItem} context.
 *
 * @remarks
 * When the field has an error, `aria-describedby` includes both the
 * {@link FormDescription} and {@link FormMessage} IDs so screen readers
 * announce both the hint and the error.
 */
function FormControl({
  render,
  ...props
}: useRender.ComponentProps<"div"> & React.ComponentProps<"div">) {
  const { error, formItemId, formDescriptionId, formMessageId } =
    useFormField();

  return useRender({
    render,
    defaultTagName: "div",
    props: mergeProps<"div">(
      {
        // Include formMessageId in describedby only when there is an error
        "aria-describedby": error
          ? `${formDescriptionId} ${formMessageId}`
          : `${formDescriptionId}`,
        "aria-invalid": !!error,
        id: formItemId,
      },
      props
    ),
    state: {
      slot: "form-control",
    },
  });
}

/**
 * Muted helper text for a react-hook-form field inside {@link FormItem}.
 *
 * Automatically receives the `id` that {@link FormControl} references in
 * `aria-describedby`, ensuring screen readers announce the hint.
 */
function FormDescription({ className, ...props }: React.ComponentProps<"p">) {
  const { formDescriptionId } = useFormField();

  return (
    <p
      className={cn("text-muted-foreground text-sm", className)}
      data-slot="form-description"
      id={formDescriptionId}
      {...props}
    />
  );
}

/**
 * Validation error message for a react-hook-form field inside
 * {@link FormItem}.
 *
 * Shows the react-hook-form `error.message` when present; falls back to
 * explicit `children`. Renders nothing when there is no message. The
 * element's `id` is referenced by {@link FormControl}'s `aria-describedby`
 * on error so screen readers announce the message.
 */
function FormMessage({
  className,
  children,
  ...props
}: React.ComponentProps<"p">) {
  const { error, formMessageId } = useFormField();
  // Prefer RHF error message; fall back to explicit children.
  const body = error ? String(error?.message) : children;

  if (!body) {
    return null;
  }

  return (
    <p
      className={cn("font-medium text-destructive text-sm", className)}
      data-slot="form-message"
      id={formMessageId}
      {...props}
    >
      {body}
    </p>
  );
}

export {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  useFormField,
};
