// scripts/generate-demo-registry.ts
// Scans apps/docs/demos for demo files and emits a static import map consumed
// by <ComponentPreview>. A generated map (rather than a dynamic import
// expression) keeps demo resolution deterministic across bundlers.
//
// Run: `bun scripts/generate-demo-registry.ts` (idempotent); also part of
// `bun run docs:generate`.
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const DEMOS_DIR = "apps/docs/demos";
const OUT_FILE = "apps/docs/src/registry/demos.generated.ts";

/** Recursively collect every `.tsx` demo file under DEMOS_DIR. */
function collectDemos(dir: string): string[] {
  if (!existsSync(dir)) {
    return [];
  }
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...collectDemos(full));
    } else if (entry.name.endsWith(".tsx")) {
      out.push(full);
    }
  }
  return out;
}

const names = collectDemos(DEMOS_DIR)
  // Demo name = path relative to demos/, without extension (e.g. button/sizes).
  .map((file) => relative(DEMOS_DIR, file).replace(/\.tsx$/, ""))
  .sort();

const entries = names
  .map((name) => `  "${name}": () => import("@/demos/${name}"),`)
  .join("\n");

const content = `// Generated by scripts/generate-demo-registry.ts — do not edit.
import type { ComponentType } from "react";

/** Demo name (relative to demos/, without extension) -> lazy module import. */
export const demoImports: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
${entries}
};
`;

mkdirSync(join(OUT_FILE, ".."), { recursive: true });
writeFileSync(OUT_FILE, content);
console.log(
  `✓ Generated demo registry with ${names.length} demos → ${OUT_FILE}`
);
